name: "内网穿透代理"
version: "1.3.17"
slug: tunnel-proxy
description: "基于自建中转服务器的Home Assistant内网穿透解决方案，支持IP和域名连接"
url: "https://github.com/RuoFeng2015/xmwp-addons"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: manual
init: false
options:
  connection_type: "domain"
  server_host: ""
  server_domain: "tunnel.wzzhk.club"
  server_port: 3080
  local_ha_port: 8123
  username: "admin"
  password: "password"
  client_id: "ha-client-001"
  proxy_port: 9001
  log_level: "info"
schema:
  connection_type:
    description: "连接类型：选择IP直连或域名连接"
    list:
      - ip
      - domain
  server_host:
    description: "服务器IP地址 (仅在连接类型为'ip'时需要填写)"
    str: true
    required: false
  server_domain:
    description: "服务器域名 (仅在连接类型为'domain'时需要填写)"
    str: true
    required: false
  server_port:
    description: "服务器端口号"
    int:
      min: 1
      max: 65535
  local_ha_port:
    description: "Home Assistant本地端口号"
    int:
      min: 1
      max: 65535
  username:
    description: "隧道服务用户名"
    str: true
  password:
    description: "隧道服务密码"
    str: true
  client_id:
    description: "客户端唯一标识符"
    str: true
  proxy_port:
    description: "本地代理服务端口"
    int:
      min: 1
      max: 65535
  log_level:
    description: "日志级别"
    list:
      - debug
      - info
      - warn
      - error
ports:
  9001/tcp: 9001
ports_description:
  9001/tcp: "代理服务端口"
map:
  - config:rw
  - ssl:rw
