name: "内网穿透代理"
version: "1.3.0"
slug: tunnel-proxy
description: "基于自建中转服务器的Home Assistant内网穿透解决方案，支持IP和域名连接"
url: "https://github.com/RuoFeng2015/xmwp-addons"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: manual
init: false
options:
  connection_type: "ip"
  server_host: "114.132.237.146"
  server_domain: "tunnel.wzzhk.club"
  server_port: 3080
  local_ha_port: 8123
  username: "admin"
  password: "password"
  client_id: "ha-client-001"
  proxy_port: 9001
  log_level: "info"
schema:
  connection_type: list(ip|domain)
  server_host: str
  server_domain: str
  server_port: int(1,65535)
  local_ha_port: int(1,65535)
  username: str
  password: str
  client_id: str
  proxy_port: int(1,65535)
  log_level: list(debug|info|warn|error)
ports:
  9001/tcp: 9001
ports_description:
  9001/tcp: "代理服务端口"
map:
  - config:rw
  - ssl:rw
